esphome:
  name: example-display
  friendly_name: Example_Display
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret display_key

ota:
  - platform: esphome
    password: !secret display_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Example-Display Fallback Hotspot"
    password: !secret display_ap

captive_portal:


image:
  - file: "weather.gif"
    id: weather_pic
    type: RGB565
    

lvgl:
  theme:
    button:
      scroll_on_focus: true
      border_width: 2
      outline_pad: 6
      pressed:
        border_color: 0xFF007F
      checked:
        border_color: 0xFFFF00
      focused:
        border_color: 0x00FF00
    switch:
      transform_angle: 0

  displays:
    - my_display
  pages:
    - id: main_page
      bg_color: 0x000077
      widgets:

        - image:
            align: TOP_LEFT
            src: weather_pic
            id: img_id
         


number:
  - platform: template
    name: Регулировка подсветки 
    id: change_backlight
    optimistic: true
    internal: True
    min_value: 0
    max_value: 100
    step: 1
    on_value:
      then:
        - light.turn_on:
            id: display_backlight
            brightness: !lambda "return x/100;"


#=========================================
#    Display
#=========================================

i2c:
  - id: bus_a
    sda: 19
    scl: 20

output:
    # Backlight LED
  - platform: ledc
    pin: GPIO2
    id: GPIO2
    frequency: 1220Hz

light:
    # Backlight
  - platform: monochromatic
    output: GPIO2
    name: Подсветка
    id: display_backlight
    restore_mode: ALWAYS_ON
    gamma_correct: 0.6
    

touchscreen:
  platform: gt911
  reset_pin: 38
  transform:
    mirror_x: false
    mirror_y: false
  id: my_touchscreen
  display: my_display

  on_touch:
    - logger.log:
        format: Touch at (%d, %d)
        args: [touch.x, touch.y]
    - lambda: |-
        ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
            );

display:
  - platform: rpi_dpi_rgb
    id: my_display
    color_order: RGB
    invert_colors: True
    update_interval: never
    auto_clear_enabled: false # takes 2.8 seconds to clear the display
    dimensions:
      width: 800
      height: 480
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 42
    pclk_frequency: 12MHz
    data_pins:
      red:
        - 14        #r1
        - 21        #r2
        - 47        #r3
        - 48        #r4
        - 45        #r5
      green:
        - 9         #g0
        - 46        #g1
        - 3         #g2
        - 8         #g3
        - 16        #g4
        - 1         #g5
      blue:
        - 15        #b1
        - 7         #b2
        - 6         #b3
        - 5         #b4
        - 4         #b5




